export { COMPANY } from "./company";
export { PROFESSIONALS } from "./professionals";
export { SERVICES } from "./services";
export { SCHEDULES } from "./schedules";
export { TECHNOLOGIES } from "./technology";
export { NAVIGATION } from "./navigation";
export { IMAGES } from "./images";
export { LABORATORY_SERVICES } from "./laboratory-services";
export { LABORATORY_PROCESS } from "./laboratory-process";
export {LOCATIONS,LABORATORY_LOCATION } from "./locations";