export const SITE_CONFIG = {
  name: "LABODENT",
  title: "LABODENT | Clínica Dental",
  description:
    "Clínica dental y laboratorio digital en Ciudad del Este Paraguay. Atención odontológica integral, tratamientos especializados, tecnología moderna y soluciones digitales para profesionales.",
  locale: "es-PY",
  openGraphLocale: "es_PY",

  url: "https://labodent-py.com",

  keywords: [
    "LABODENT",
    "clínica dental",
    "odontología",
    "odontólogo",
    "dentista",
    "implantes dentales",
    "implantología",
    "ortodoncia",
    "endodoncia",
    "estética dental",
    "odontopediatría",
    "rehabilitación oral",
    "odontología Ciudad del Este",
    "dentista Ciudad del Este",
    "odontología Tembiaporã",
    "clínica dental Paraguay",
    "laboratorio dental",
    "laboratorio digital dental",
    "escáner intraoral 3D",
    "diseño dental digital",
    "prótesis dentales",
    "carillas dentales",
  ],
} as const;